import { useEffect, useState } from "react";
import { askQuestion, getDocuments, indexDocument } from "./api";
import "./styles.css";

export default function App() {
  const [documents, setDocuments] = useState([]);
  const [storedChunkCount, setStoredChunkCount] = useState(0);
  const [selectedFile, setSelectedFile] = useState(null);
  const [question, setQuestion] = useState("");
  const [messages, setMessages] = useState([]);
  const [status, setStatus] = useState("");
  const [error, setError] = useState("");
  const [isIndexing, setIsIndexing] = useState(false);
  const [isAsking, setIsAsking] = useState(false);

  async function refreshDocuments() {
    const data = await getDocuments();
    setDocuments(data.documents);
    setStoredChunkCount(data.stored_chunk_count);
  }

  useEffect(() => {
    refreshDocuments().catch((err) => {
      setError(err.message);
    });
  }, []);

  async function handleIndex(event) {
    event.preventDefault();

    if (!selectedFile) {
      setError("Choose a PDF, TXT, or DOCX file first.");
      return;
    }

    setError("");
    setStatus("Indexing document with local Ollama embeddings...");
    setIsIndexing(true);

    try {
      const result = await indexDocument(selectedFile);
      setStatus(
        `Indexed ${result.filename}: ${result.chunk_count} chunks stored locally.`,
      );
      setSelectedFile(null);
      event.target.reset();
      await refreshDocuments();
    } catch (err) {
      setError(err.message);
      setStatus("");
    } finally {
      setIsIndexing(false);
    }
  }

  async function handleAsk(event) {
    event.preventDefault();

    const trimmedQuestion = question.trim();
    if (!trimmedQuestion) {
      setError("Ask a question first.");
      return;
    }

    setError("");
    setQuestion("");
    setIsAsking(true);
    setMessages((current) => [
      ...current,
      { role: "user", content: trimmedQuestion },
    ]);

    try {
      const result = await askQuestion(trimmedQuestion);
      setMessages((current) => [
        ...current,
        {
          role: "assistant",
          content: result.answer,
          sources: result.sources,
        },
      ]);
    } catch (err) {
      setError(err.message);
    } finally {
      setIsAsking(false);
    }
  }

  return (
    <main className="app-shell">
      <aside className="sidebar">
        <section className="brand">
          <h1>AI Document Analyzer</h1>
          <p>
            Local RAG over your PDFs, TXT files, and Word documents. No paid API
            keys, no cloud vector database.
          </p>
        </section>

        <form className="upload-panel" onSubmit={handleIndex}>
          <label htmlFor="document-upload">
            <strong>Upload and index</strong>
          </label>
          <input
            id="document-upload"
            className="file-input"
            type="file"
            accept=".pdf,.txt,.docx"
            onChange={(event) => setSelectedFile(event.target.files[0])}
          />
          <button className="primary-button" disabled={isIndexing} type="submit">
            {isIndexing ? "Indexing..." : "Index document"}
          </button>
          <p className="hint">
            Indexing parses, chunks, embeds, and stores vectors in local
            ChromaDB.
          </p>
        </form>

        <section>
          <h3>Documents</h3>
          <div className="document-list">
            {documents.length === 0 ? (
              <p className="meta">No uploaded documents yet.</p>
            ) : (
              documents.map((document) => (
                <div className="document-item" key={document.filename}>
                  <div className="document-name">{document.filename}</div>
                  <div className="meta">
                    {(document.size_bytes / 1024).toFixed(1)} KB
                  </div>
                </div>
              ))
            )}
          </div>
          <p className="meta">{storedChunkCount} chunks stored in ChromaDB.</p>
        </section>
      </aside>

      <section className="main-panel">
        <header className="topbar">
          <h2>Ask Your Documents</h2>
          <p className="meta">
            Answers are generated by local Ollama using retrieved source chunks.
          </p>
        </header>

        <section className="messages">
          {messages.length === 0 ? (
            <div className="empty-state">
              <h3>Start with a document question</h3>
              <p>
                Try questions like “What is this assignment about?” or “What are
                the deliverables?” after indexing a document.
              </p>
            </div>
          ) : (
            messages.map((message, index) => (
              <article className={`message ${message.role}`} key={index}>
                <p className="message-label">
                  {message.role === "user" ? "You" : "Assistant"}
                </p>
                <div className="answer">{message.content}</div>

                {message.sources?.length > 0 && (
                  <div className="sources">
                    {message.sources.map((source) => (
                      <div className="source" key={source.source_number}>
                        <div className="source-title">
                          Source {source.source_number}: {source.source_file},
                          page {source.page_number}, chunk {source.chunk_id}
                        </div>
                        <div className="meta">
                          distance {source.distance.toFixed(4)}
                        </div>
                        <div className="source-preview">
                          {source.text_preview}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </article>
            ))
          )}
        </section>

        <footer className="composer">
          <form className="composer-form" onSubmit={handleAsk}>
            <textarea
              placeholder="Ask a question about the indexed documents..."
              value={question}
              onChange={(event) => setQuestion(event.target.value)}
            />
            <button className="primary-button" disabled={isAsking} type="submit">
              {isAsking ? "Thinking..." : "Ask"}
            </button>
          </form>
          <div className="status">{status}</div>
          {error && <div className="error">{error}</div>}
        </footer>
      </section>
    </main>
  );
}
